# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv:
  - ./.env

vars:
  DBURL: postgres://{{.DB_USER}}:{{.DB_PASSWORD}}@{{.DB_HOST}}:{{.DB_PORT}}/{{.DB_NAME}}?sslmode=disable

tasks:
  default:
    cmds:
      - task: run

  run:
    cmd: go run ./cmd/server/main.go

  migrate:up:
    desc: Apply all migrations
    cmd: goose -dir ./migrations postgres "{{.DBURL}}" up

  migrate:down:
    desc: Down all migrations
    cmd: goose -dir ./migrations postgres "{{.DBURL}}" down

  migrate:status:
    desc: Status migrate
    cmd: goose -dir ./migrations postgres "{{.DBURL}}" status
